require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
